### ISSUE TITLE
běžící orchestrace mají nullový `lastScheduledTime`

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/orchestrator-bundle#10]
![untitled_text_6_and__test__syrup_devel_-_orchestrations_and_developer_tools_-_https___connection_keboola_com_admin_projects_395_orchestrations_66819400](https://cloud.githubusercontent.com/assets/497675/14488740/efc8ea96-0169-11e6-967c-eb0fcf23c52c.png)

**Comment by ErikZigo** [comment]
Takhle to funguje od zacatku. Podivam se na to, zjistim jestli to nebude mit na neco dopad. Pripadne to fixnu

**Comment by ErikZigo** [comment]
Znovu jsem se na to koukal. 

"lastScheduledTime" znamena posledni cas, kdy scheduler vytvoril job

V tomhle tvym pripade mas orchestraci, kterou spoustis manualne. Takze proto tam je null vzdycky.

Do toho sloupce v UI by se tedy mel spis nacitat "lastExecutedJob.startTime" dam si to jako issue do UI

**Comment by ondrejhlavacek** [comment]
Super, díky!

2016-04-29 18:32 GMT+02:00 Erik Zigo <notifications@github.com>:

> Znovu jsem se na to koukal.
>
> "lastScheduledTime" znamena posledni cas, kdy scheduler vytvoril job
>
> V tomhle tvym pripade mas orchestraci, kterou spoustis manualne. Takze
> proto tam je null vzdycky.
>
> Do toho sloupce v UI by se tedy mel spis nacitat
> "lastExecutedJob.startTime" dam si to jako issue do UI
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/orchestrator-bundle/issues/10#issuecomment-215796490>
>



-- 
Ondrej Hlavacek
Developer, Keboola
+420 777 930 888
@keboola
