### ISSUE TITLE
Email notifications, identify project in the subject of the email

### ISSUE THREAD

**Issue by kacurez** [keboola/orchestrator-bundle#13]
BUG: Zmen subject emailu s notifikaci orchestratoru tak, ze neni mozne identifikovat projekt, ke kteremu notifikace patri.

Neda se to vratit? Nemame podle ceho potom ty notifikace smerovat v IFTTT do spravnyho kanalu podle projektu.

**Comment by padak** [comment]
Tohle není bug, maj mít pagerduty emaily v orchestraci a ne parser email subjektů.

**Comment by ondrejhlavacek** [comment]
Oni na to používaj pagerduty? Ještě se dá použít ten gmailovej adresní hack.

**Comment by ErikZigo** [comment]
Podle me to bug, neni tak jsem to zrusil.
Koukal jsem do historie orchestratoru a orchestrator v syrupu to nikdy tak nemel.
Kdyz kouknu na stary orchestrator v Zendu, tak to tam taky nevidim

**Comment by padak** [comment]
@ondrejhlavacek podle všeho právě ne - přijde mi, že si udělali pravidlo pro IFTTT (!!) a to jim selhalo, jakmile se něco změnilo

**Comment by ErikZigo** [comment]
Napsal jsem R v tom ticketu.

Nejak tomu vubec nerozumim. PID tam v zivote nebyl, Project Name tam je porad.
S posilanim emailu se nic nemenilo 4 mesice.

**Comment by kacurez** [comment]
tak nakoniec R uznal ze to tam nikdy nebolo. By som to uzavrel, sorry za zmatky.
