### ISSUE TITLE
názvy projektů v notifikačních mailech

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/orchestrator-bundle#17]
pokud přejmenuju projekt, tak v mailu stále chodí jeho starý název

https://keboola.slack.com/archives/orchestrator/p1464941147000002
https://keboola.zendesk.com/agent/tickets/4976

**Comment by ErikZigo** [comment]
fixed in dab0862dcc231e58a388d90ca8ae896e96049bef
