### ISSUE TITLE
500 on wrong orch. schedule?

### ISSUE THREAD

**Issue by ujovlado** [keboola/orchestrator-bundle#31]
`orchestrator-bb5a38445391a2f01ef8f98799a3110e`

zadal som tam 31.2.

**Comment by ujovlado** [comment]
asi by stacilo to dat na user error

**Comment by ErikZigo** [comment]
Jo spravne by se to melo vratit jako user error. Fixnu to, az budu fixovat jiny dalsi issue co mam od najlose

**Comment by ErikZigo** [comment]
fixnuto a nasazeno
