### ISSUE TITLE
Zbavit se timeout-bundlu

### ISSUE THREAD

**Issue by ErikZigo** [keboola/orchestrator-bundle#46]
Orchestrator v testech vyuziva `timeout` komponentu pro simulaci sync akci, error stavu a maintenance projektu.

Komponenta `timeout` se k nicemu jinymu v KBC nepouziva. Chceme se ji zbavit stejne jako dalsich starych komponent postavenych na syrupu.

**Comment by Halama** [comment]
Vyřešeno https://github.com/keboola/docker-bundle/issues/52#issuecomment-350018016
