### ISSUE TITLE
Apiary Create orchestration misleading

### ISSUE THREAD

**Issue by Halama** [keboola/orchestrator-bundle#49]
říká to že při vytvoření orchestrace to k ní uloží aktuální token, není to ale pravda vytváří to nový.

> Create a new Orchestration. Current token will be saved with orchestration to be able to execute jobs. You can change assigned token later.

**Comment by ErikZigo** [comment]
Fixed https://keboolaorchestratorv2api.docs.apiary.io/#reference/orchestrations/orchestrations-collection/create-a-orchestration
