### ISSUE TITLE
Orchestration create with tokenId

### ISSUE THREAD

**Issue by Halama** [keboola/orchestrator-bundle#50]
Při zakládání orchestrace s nastaveným `tokenId` zařve `Token has no permissions for token manipulation`. Pokud tomu ten token předám tak nepotřebuje práva na manipulaci tokenů ne?

![image](https://user-images.githubusercontent.com/903531/33422407-e8603e36-d5b5-11e7-81f2-f190eb8bcbd4.png)

**Comment by ErikZigo** [comment]
Ja se na to podivam. Asi je to pozustatek z davne doby.
Mam dojem ze driv jiny nez manage token nemel prava pristupu ke konfiguracim.

**Comment by Halama** [comment]
jo je to tak že když má nastavené `canManageBuckets` tak může ke komponentám. Pokud by tohle šlo fixnout bylo by to super odblokovalo by to pak možnost skriptovat projekty.

**Comment by ErikZigo** [comment]
Zitra uz bude nasazene v produkci

**Comment by ErikZigo** [comment]
Minuly tyden nasazeno a  typkovi odpovezeno v ticketu.
