### ISSUE TITLE
If there are no tasks, log a warning and return success?

### ISSUE THREAD

**Issue by pivnicek** [keboola/orchestrator-bundle#85]
Currently the case is if you run an orch with no tasks it has error status.  But, it didn't really error did it?  I mean it didn't do anything, but that seems like correct behaviour, so should return success (with a warning?)

**Comment by odinuv** [comment]
how did you do it? it gives a warning in the ui 

![image](https://user-images.githubusercontent.com/4319320/54114090-e92d1e80-43e9-11e9-94b7-d95f160f82be.png)

**Comment by pivnicek** [comment]
I imagine they ran it via api

**Comment by odinuv** [comment]
seems valid to me then to end it with an error - it's probably not doing (nothing) what you expect it is doing (something)

**Comment by pivnicek** [comment]
:-) this could get philosophical.  But it does what it should (nothing) so that seems like success to me:).  Although there should definitely be a warning that it didn't do anything.  Anyhow, this seems very low priority imho.
