### ISSUE TITLE
Retry: Job specification must containts all orchestrations tasks

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/orchestrator-bundle#87]
1) Pustit orchestraci, co vyfailuje (https://connection.keboola.com/admin/projects/232/orchestrations/490170441/jobs/490634705)
2) Do orchestrace přidat task
3) Dát retry orchestrace

=> 

![image](https://user-images.githubusercontent.com/497675/54743196-c78b1e80-4bc3-11e9-9a87-12035ea7706c.png)

```
{"status":"warning","message":"Job specification must containts all orchestrations tasks","code":"JOB_VALIDATION"}
```

btw v té hlášce je překlep, `Job specification must contain all orchestration tasks.`

**Comment by ondrejhlavacek** [comment]
ref https://keboola.zendesk.com/agent/tickets/10089

**Comment by ErikZigo** [comment]
No to nejde no. Vzdycky se to validuje oproti aktulani konfiguraci.

**Comment by ondrejhlavacek** [comment]
Mohlo by to třeba říct nějakou lepší hlášku?

**Comment by odinuv** [comment]
dup dup https://github.com/keboola/orchestrator-bundle/issues/73

**Comment by ondrejhlavacek** [comment]
pecka :-)
